### ISSUE TITLE
Boundaries and Whitespace are not working

### ISSUE THREAD

**Issue by runxel** [Mohd-PH/RegexSearch#17]
`\s` and `\b` are not working as expected. Instead the search result will be prolonged until the html tag closes or a `<br>` is encountered.

Firefox 67.0.4

**Comment by SaltatorMortis** [comment]
can you give the problematic site with your regex? 
maybe add a description what you want to select.

i think you run into a "copyright protection" variation or a rare case where innerText != RenderedText


cause otherwise its working as intended ie, 
/issue[^\s]+/gi gives 2 matches
/\bissue\b/gi gives two matches

**Comment by runxel** [comment]
Okay, it seems that restarting Firefox helped there. It works now. ¯\_(ツ)_/¯
